export const fakeImage = {
  id: "abc123",
  created_at: "2025-06-06T12:00:00-04:00",
  updated_at: "2025-06-06T12:00:00-04:00",
  width: 4000,
  height: 3000,
  color: "#aabbcc",
  blur_hash: "L5H2EC=PM+yV0g-mq.wG9c010J}I",
  likes: 42,
  liked_by_user: false,
  description: "Un paysage de montagne au lever du soleil.",
  user: {
    id: "user001",
    username: "mountain_lover",
    name: "Alice Dupont",
    portfolio_url: "https://example.com",
    bio: "Photographe passionnée par la nature.",
    location: "Alpes françaises",
    total_likes: 100,
    total_photos: 200,
    total_collections: 10,
    instagram_username: "alice.photos",
    twitter_username: "alice_tweet",
    profile_image: {
      small: "https://randomuser.me/api/portraits/women/1.jpg",
      medium: "https://randomuser.me/api/portraits/women/1.jpg",
      large: "https://randomuser.me/api/portraits/women/1.jpg",
    },
    links: {
      self: "#",
      html: "#",
      photos: "#",
      likes: "#",
      portfolio: "#",
    },
  },
  current_user_collections: [],
  urls: {
    raw: "https://picsum.photos/id/1018/4000/3000",
    full: "https://picsum.photos/id/1018/1920/1080",
    regular: "https://picsum.photos/id/1018/1080/720",
    small: "https://picsum.photos/id/1018/400/300",
    thumb: "https://picsum.photos/id/1018/200/150",
  },
  links: {
    self: "#",
    html: "#",
    download: "https://picsum.photos/id/1018/1920/1080",
    download_location: "#",
  },
};
