### GET All Users
GET http://localhost:3000/api/users/



###  POST create User
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "email": "ychnightder77375@doe.com",
  "password": "ychnightder"
}

### GET User
GET http://localhost:3000/api/users/ychnightder73%40doe.com


### DELETE User
DELETE http://localhost:3000/api/users/124

