### GET All Collections
GET http://localhost:3000/api/Collections/



###  POST create Collection
POST http://localhost:3000/api/Collections
Content-Type: application/json

{
  "name": "montage"
}

### GET Collection
GET http://localhost:3000/api/Collections/1


### DELETE Collection
DELETE http://localhost:3000/api/Collections/10

